### ISSUE TITLE
Cloudflare page building is failing on push to main

### ISSUE THREAD

**Issue by ttshivers** [vrchatapi/specification#322]
It appears that the cloudflare building check is failing on main now after my changes in https://github.com/vrchatapi/specification/pull/318

Ex: https://github.com/vrchatapi/specification/runs/24226379233

I can't view the logs so I don't know why.

**Comment by Foorack** [comment]
Thanks, will check.

**Comment by Foorack** [comment]
@ttshivers 
```
2024-04-24T22:42:38.34656Z	Cloning repository...
2024-04-24T22:42:38.9768Z	From https://github.com/vrchatapi/specification
2024-04-24T22:42:38.977297Z	 * branch            1b8686b43c0038091849dec936d57423ae7a3358 -> FETCH_HEAD
2024-04-24T22:42:38.977402Z	
2024-04-24T22:42:39.019215Z	HEAD is now at 1b8686b fix(notification):  Include notification details (#318)
2024-04-24T22:42:39.019728Z	
2024-04-24T22:42:39.099312Z	
2024-04-24T22:42:39.121487Z	Success: Finished cloning repository files
2024-04-24T22:42:40.364467Z	Checking for configuration in a wrangler.toml configuration file (BETA)
2024-04-24T22:42:40.365466Z	
2024-04-24T22:42:40.485833Z	No wrangler.toml file found. Continuing.
2024-04-24T22:42:40.577798Z	Installing dependencies
2024-04-24T22:42:40.583008Z	Python version set to 2.7
2024-04-24T22:42:42.621269Z	v12.18.0 is already installed.
2024-04-24T22:42:43.372817Z	Now using node v12.18.0 (npm v6.14.4)
2024-04-24T22:42:43.497293Z	Started restoring cached build plugins
2024-04-24T22:42:43.505628Z	Finished restoring cached build plugins
2024-04-24T22:42:43.770565Z	Attempting ruby version 2.7.1, read from environment
2024-04-24T22:42:44.913881Z	Using /opt/buildhome/.rvm/gems/ruby-2.7.1
2024-04-24T22:42:45.522672Z	Using PHP version 5.6
2024-04-24T22:42:45.594782Z	5.2.5 is already installed.
2024-04-24T22:42:45.608021Z	Using Swift version 5.2.5
2024-04-24T22:42:45.608318Z	Started restoring cached node modules
2024-04-24T22:42:45.615962Z	Finished restoring cached node modules
2024-04-24T22:42:45.83869Z	Installing NPM modules using NPM version 6.14.4
2024-04-24T22:42:46.945562Z	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
2024-04-24T22:42:52.327399Z	
2024-04-24T22:42:52.327607Z	> core-js@3.37.0 postinstall /opt/buildhome/repo/node_modules/core-js
2024-04-24T22:42:52.327795Z	> node -e "try{require('./postinstall')}catch(e){}"
2024-04-24T22:42:52.327898Z	
2024-04-24T22:42:52.40037Z	[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2024-04-24T22:42:52.400549Z	
2024-04-24T22:42:52.400633Z	[96mThe project needs your help! Please consider supporting core-js:[0m
2024-04-24T22:42:52.400735Z	[96m>[94m https://opencollective.com/core-js [0m
2024-04-24T22:42:52.40085Z	[96m>[94m https://patreon.com/zloirock [0m
2024-04-24T22:42:52.400953Z	[96m>[94m https://boosty.to/zloirock [0m
2024-04-24T22:42:52.401047Z	[96m>[94m bitcoin: bc1qlea7544qtsmj2rayg0lthvza9fau63ux0fstcz [0m
2024-04-24T22:42:52.401141Z	
2024-04-24T22:42:52.401225Z	[96mI highly recommend reading this:[94m https://github.com/zloirock/core-js/blob/master/docs/2023-02-14-so-whats-next.md [96m[0m
2024-04-24T22:42:52.401309Z	
2024-04-24T22:42:52.587182Z	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2024-04-24T22:42:52.58778Z	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2024-04-24T22:42:52.588309Z	
2024-04-24T22:42:52.589843Z	added 349 packages from 296 contributors and audited 350 packages in 5.67s
2024-04-24T22:42:52.672715Z	
2024-04-24T22:42:52.672976Z	64 packages are looking for funding
2024-04-24T22:42:52.673144Z	  run `npm fund` for details
2024-04-24T22:42:52.673258Z	
2024-04-24T22:42:52.6735Z	found 5 vulnerabilities (3 moderate, 2 critical)
2024-04-24T22:42:52.673651Z	  run `npm audit fix` to fix them, or `npm audit` for details
2024-04-24T22:42:52.688893Z	NPM modules installed
2024-04-24T22:42:52.720273Z	Installing Hugo 0.54.0
2024-04-24T22:42:53.538477Z	Hugo Static Site Generator v0.54.0-B1A82C61A/extended linux/amd64 BuildDate: 2019-02-01T10:04:38Z
2024-04-24T22:42:53.540539Z	Started restoring cached go cache
2024-04-24T22:42:53.550758Z	Finished restoring cached go cache
2024-04-24T22:42:53.620713Z	go version go1.14.4 linux/amd64
2024-04-24T22:42:53.630096Z	go version go1.14.4 linux/amd64
2024-04-24T22:42:53.632832Z	Installing missing commands
2024-04-24T22:42:53.633317Z	Verify run directory
2024-04-24T22:42:53.633587Z	Executing user command: npm run bundle
2024-04-24T22:42:53.870915Z	
2024-04-24T22:42:53.871184Z	> vrchat-openapi-test@1.0.0 bundle /opt/buildhome/repo
2024-04-24T22:42:53.871323Z	> node ./node_modules/\@redocly/cli/bin/cli.js bundle openapi/openapi.yaml -o dist/openapi.yaml
2024-04-24T22:42:53.871439Z	
2024-04-24T22:42:54.193665Z	/opt/buildhome/repo/node_modules/get-port-please/dist/index.cjs:259
2024-04-24T22:42:54.193911Z	  const _port = Number(_userOptions.port ?? process.env.PORT);
2024-04-24T22:42:54.194246Z	                                          ^
2024-04-24T22:42:54.19438Z	
2024-04-24T22:42:54.194473Z	SyntaxError: Unexpected token '?'
2024-04-24T22:42:54.194563Z	    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
2024-04-24T22:42:54.194647Z	    at Module._compile (internal/modules/cjs/loader.js:1102:27)
2024-04-24T22:42:54.194755Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2024-04-24T22:42:54.194825Z	    at Module.load (internal/modules/cjs/loader.js:986:32)
2024-04-24T22:42:54.194895Z	    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
2024-04-24T22:42:54.194959Z	    at Module.require (internal/modules/cjs/loader.js:1026:19)
2024-04-24T22:42:54.195024Z	    at require (internal/modules/cjs/helpers.js:72:18)
2024-04-24T22:42:54.195105Z	    at Object.<anonymous> (/opt/buildhome/repo/node_modules/@redocly/cli/lib/commands/preview-docs/preview-server/preview-server.js:14:27)
2024-04-24T22:42:54.195183Z	    at Module._compile (internal/modules/cjs/loader.js:1138:30)
2024-04-24T22:42:54.195259Z	    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
2024-04-24T22:42:54.19969Z	npm ERR! code ELIFECYCLE
2024-04-24T22:42:54.199857Z	npm ERR! errno 1
2024-04-24T22:42:54.200789Z	npm ERR! vrchat-openapi-test@1.0.0 bundle: `node ./node_modules/\@redocly/cli/bin/cli.js bundle openapi/openapi.yaml -o dist/openapi.yaml`
2024-04-24T22:42:54.200952Z	npm ERR! Exit status 1
2024-04-24T22:42:54.201038Z	npm ERR! 
2024-04-24T22:42:54.201215Z	npm ERR! Failed at the vrchat-openapi-test@1.0.0 bundle script.
2024-04-24T22:42:54.201392Z	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2024-04-24T22:42:54.205392Z	
2024-04-24T22:42:54.205565Z	npm ERR! A complete log of this run can be found in:
2024-04-24T22:42:54.20568Z	npm ERR!     /opt/buildhome/.npm/_logs/2024-04-24T22_42_54_201Z-debug.log
2024-04-24T22:42:54.213324Z	Failed: build command exited with code: 1
2024-04-24T22:42:55.059224Z	Failed: error occurred while running build command
```

**Comment by Foorack** [comment]
It seems #318 indirectly added a dependency on `get-port-please`, which is causing the error.

**Comment by Foorack** [comment]
We are running on Build Environment 1, which ships Node 12.

I'll try upgrade to Build Environment 2, which ships Node 18.

**Comment by Foorack** [comment]
It passes now. Thank you for the report! Will close the issue, please comment if still facing this problem.
