### ISSUE TITLE
Instance.roleRestricted is nullable

### ISSUE THREAD

**Issue by Rexios80** [vrchatapi/specification#323]
```console

DioException [unknown]: null
Error: CheckedFromJsonException
Could not create `Instance`.
There is a problem with "roleRestricted".
Required keys are missing: roleRestricted.
#0      WorldsApi.getWorldInstance (package:vrchat_dart_generated/src/api/worlds_api.dart:678)
<asynchronous suspension>
#1      DioResponseValidator.validate (package:dio_response_validator/src/dio_response_validator_base.dart:16)
<asynchronous suspension>
#2      WorldDetailController.init (package:zenith/controller/world_detail_controller.dart:19)
<asynchronous suspension>

```

**Comment by Rexios80** [comment]
This was already fixed. I was using an outdated version of the spec.
